SELECT (select instance_number from v$instance) inst_id,
       COMPONENT,
       CURRENT_SIZE / (1024 * 1024) AS CURRENT_SIZE,
       MIN_SIZE / (1024 * 1024) AS MIN_SIZE,
       MAX_SIZE / (1024 * 1024) AS MAX_SIZE,
       USER_SPECIFIED_SIZE / (1024 * 1024) AS USER_SPECIFIED_SIZE,
       OPER_COUNT,
       LAST_OPER_TYPE,
       GRANULE_SIZE / (1024 * 1024) AS GRANULE_SIZE
  FROM V$MEMORY_DYNAMIC_COMPONENTS
 ORDER BY USER_SPECIFIED_SIZE desc,CURRENT_SIZE desc;
