-- 查看redo日志切换频率  

SELECT DAY,
       to_char(SUM(decode(h,
                          '00',
                          t,
                          0))) AS "00",
       to_char(SUM(decode(h,
                          '01',
                          t,
                          0))) AS "01",
       to_char(SUM(decode(h,
                          '02',
                          t,
                          0))) AS "02",
       to_char(SUM(decode(h,
                          '03',
                          t,
                          0))) AS "03",
       to_char(SUM(decode(h,
                          '04',
                          t,
                          0))) AS "04",
       to_char(SUM(decode(h,
                          '05',
                          t,
                          0))) AS "05",
       to_char(SUM(decode(h,
                          '06',
                          t,
                          0))) AS "06",
       to_char(SUM(decode(h,
                          '07',
                          t,
                          0))) AS "07",
       to_char(SUM(decode(h,
                          '08',
                          t,
                          0))) AS "08",
       to_char(SUM(decode(h,
                          '09',
                          t,
                          0))) AS "09",
       to_char(SUM(decode(h,
                          '10',
                          t,
                          0))) AS "10",
       to_char(SUM(decode(h,
                          '11',
                          t,
                          0))) AS "11",
       to_char(SUM(decode(h,
                          '12',
                          t,
                          0))) AS "12",
       to_char(SUM(decode(h,
                          '13',
                          t,
                          0))) AS "13",
       to_char(SUM(decode(h,
                          '14',
                          t,
                          0))) AS "14",
       to_char(SUM(decode(h,
                          '15',
                          t,
                          0))) AS "15",
       to_char(SUM(decode(h,
                          '16',
                          t,
                          0))) AS "16",
       to_char(SUM(decode(h,
                          '17',
                          t,
                          0))) AS "17",
       to_char(SUM(decode(h,
                          '18',
                          t,
                          0))) AS "18",
       to_char(SUM(decode(h,
                          '19',
                          t,
                          0))) AS "19",
       to_char(SUM(decode(h,
                          '20',
                          t,
                          0))) AS "20",
       to_char(SUM(decode(h,
                          '21',
                          t,
                          0))) AS "21",
       to_char(SUM(decode(h,
                          '22',
                          t,
                          0))) AS "22",
       to_char(SUM(decode(h,
                          '23',
                          t,
                          0))) AS "23"
  FROM (SELECT to_char(first_time,
                       'YYYY-MM-DD') DAY,
               to_char(first_time,
                       'HH24') h,
               COUNT(1) t
          FROM v$log_history
         WHERE first_time > SYSDATE - 15
         GROUP BY to_char(first_time,
                          'YYYY-MM-DD'),
                  to_char(first_time,
                          'HH24')
         ORDER BY 1)
 GROUP BY DAY
 ORDER BY DAY DESC;